name: CICD

on:
  push:
    branches: [app-demo-one]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name : Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install
      - name: Docker Login
        run: docker login -u ${{secrets.DOCKHUB_UID}} -p ${{secrets.DOCKHUB_PWD}}
      - name: Build docker image
        run: docker build -t itzmedinesh/appone .
      - name: Push image to docker hub
        run: docker push itzmedinesh/appone:latest

